@startuml
skinparam classAttributeIconSize 0

abstract DefaultPlate{
+getMeat():String[]
+setMeat(meat:String[]):void
+getVeg():String[]
+setVeg(veg:String[]):void
+getSide():String[]
+setSide(side:String[]):void
}

DefaultPlate <-- FirstPlate
DefaultPlate <-- SecondPlate
DefaultPlate -- PlateFactory
PlateFactory -- PlateTest
@enduml