@startuml
skinparam classAttributeIconSize 0

class Dessert{
    - firstInstance: Dessert
    + getInstance(): Dessert
    getDessert(): Constable
}

class DessertTest{
+main(): void
}

DessertTest --> Dessert
@enduml